import{i as h}from"./assets/vendor-17o45ynk.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const g="46278003-3664944736e49f9bfa5b8ba34",y="https://pixabay.com/api/";function L(n){const t=new URLSearchParams(n);return fetch(`${y}?key=${g}&${t}`).then(o=>{if(!o.ok)throw new Error("Something went wrong");return o.json()}).catch(o=>{throw new Error(o.message)})}function w(n,t){const{hits:o}=n,s=o.map(({webformatURL:e,largeImageURL:r,tags:i,likes:f,views:m,comments:d,downloads:p})=>`<li class="gallery-item">
              <a href="${r}" class="gallery-link">
                  <img src="${e}" alt="${i}" class="gallery-image" />
              </a>
              <div class="info">
                  <p class="info-item"><span>Likes</span> ${f}</p>
                  <p class="info-item"><span>Views</span> ${m}</p>
                  <p class="info-item"><span>Comments</span> ${d}</p>
                  <p class="info-item"><span>Downloads</span> ${p}</p>
              </div>
          </li>`).join("");t.innerHTML=s}function a(n){h.error({title:"Error",message:n})}const c=document.querySelector(".form"),S=document.querySelector(".input"),u=document.querySelector(".loader"),l=document.querySelector(".gallery");function b(){u.classList.add("is-hidden")}function P(){u.classList.remove("is-hidden")}c.addEventListener("submit",n=>{n.preventDefault();const t=S.value.trim();if(t===""){a("Sorry, there are no images matching your search query. Please try again!");return}const o={q:t,image_type:"photo",orientation:"horizontal",safesearch:!0};l.innerHTML="",P(),L(o).then(s=>{if(b(),s.hits.length===0){a("Sorry, there are no images matching your search query. Please try again!");return}w(s,l),c.reset()}).catch(s=>{a("Something went wrong. Please try again later.")})});const $=new SimpleLightbox(".gallery a");$.refresh();
//# sourceMappingURL=index.js.map
