import{i as h}from"./assets/vendor-17o45ynk.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const g="46278003-3664944736e49f9bfa5b8ba34",y="https://pixabay.com/api/";function L(s){const t=new URLSearchParams(s);return fetch(`${y}?key=${g}&${t}`).then(o=>{if(!o.ok)throw new Error("Something went wrong");return o.json()}).catch(o=>{throw new Error(o.message)})}function w(s,t){const{hits:o}=s,n=o.map(({webformatURL:e,largeImageURL:r,tags:i,likes:f,views:m,comments:d,downloads:p})=>`<li class="gallery-item">
              <a href="${r}" class="gallery-link">
                  <img src="${e}" alt="${i}" class="gallery-image" />
              </a>
              <div class="info">
                  <p class="info-item"><span>Likes</span> ${f}</p>
                  <p class="info-item"><span>Views</span> ${m}</p>
                  <p class="info-item"><span>Comments</span> ${d}</p>
                  <p class="info-item"><span>Downloads</span> ${p}</p>
              </div>
          </li>`).join("");t.innerHTML=n}function c(s){h.error({title:"Error",message:s})}const l=document.querySelector(".form"),v=document.querySelector(".input"),a=document.querySelector(".loader"),u=document.querySelector(".gallery");function S(){a.classList.remove("active"),a.classList.add("hidden")}function b(){a.classList.remove("hidden"),a.classList.add("active")}l.addEventListener("submit",s=>{s.preventDefault();const t=v.value.trim();if(t===""){c("Sorry, there are no images matching your search query. Please try again!");return}const o={q:t,image_type:"photo",orientation:"horizontal",safesearch:!0};u.innerHTML="",b(),L(o).then(n=>{if(S(),n.hits.length===0){c("Sorry, there are no images matching your search query. Please try again!");return}w(n,u)}).catch(n=>{c("Something went wrong. Please try again later.")}),l.reset()});const P=new SimpleLightbox(".gallery a");P.refresh();
//# sourceMappingURL=index.js.map
